version: '2.4'

services:
  relay_coin_nginx:
    container_name: relay-coin-nginx
    image: nginx
    cpus: 1
    mem_limit: 512M
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "9000:9000"
    depends_on:
      - relay_coin
    networks:
      - relay_net

  relay_coin_postgres14:
    image: postgres:14-alpine
    container_name: relay_coin_db
    cpus: 1
    mem_limit: 1024M
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - relay_net


  relay_coin:
    container_name: relay-coin
    cpus: 1
    mem_limit: 1024M
    build:
      context: ../backend
    restart: unless-stopped
    depends_on:
      relay_coin_postgres14:
        condition: service_healthy
    networks:
      - relay_net

networks:
  relay_net:
    driver: bridge
